### PR TITLE
[Communication] - Identifiers - Init for user and unknown dropping _

### PR DESCRIPTION
**Pull request by JoshuaLai**

### CODE REVIEW

**Comment by JoshuaLai** [comment]
Related to https://github.com/Azure/Communication/issues/227

**Comment by JoshuaLai** [comment]
Pending update to Changelog if we are going to re-introduce this change

**Comment by tjprescott** [comment]
Generally, I would say the original code is correct from the Swift user perspective and we should no break that for the sake of ObjC. Perhaps instead of using `@objcMembers` we declare `@objc` on individual members and do not expose `init(_ identifier:)` with `@objc`, instead only exposing the `init(identifier:)` to ObjC using a technique described here (https://izziswift.com/how-to-expose-swift-functions-only-to-objc/).

**Comment by JoshuaLai** [comment]
> Generally, I would say the original code is correct from the Swift user perspective and we should not break that for the sake of ObjC. Perhaps instead of using `@objcMembers` we declare `@objc` on individual members and do not expose `init(_ identifier:)` with `@objc`, instead only exposing the `init(identifier:)` to ObjC using a technique described here (https://izziswift.com/how-to-expose-swift-functions-only-to-objc/).

Are you suggesting we just change the object to 
```
public class CommunicationUserIdentifier: NSObject, CommunicationIdentifier {
    @objc public let identifier: String
    @objc(initWithIdentifier:)
    public init(_ identifier: String) {
        self.identifier = identifier
    }
}
```
I was actually wondering if it would make more sense to change the method to `init(with identifer:` I feel like that would at least create some consistency between Swift and ObjC.

**Review by tjprescott — CHANGES_REQUESTED** [review]
Needs changelog entry. I am onboard with the ObjC naming if you think it's better for you customers.

**Comment by JoshuaLai** [comment]
@tjprescott @raosanat Updated the change log with the new breaking change.

**Review by tjprescott — APPROVED** [review]

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
