### PR TITLE
Initial restructure of repo.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR restructures the libraries in the iOS repo to match the rough pattern we use across the rest of the Azure SDK repositories. Still working out many of the details about how we make this build correctly together via the Cocoapods tooling (core builds, but dependents don't).

This compliments this PR:

https://github.com/Azure/azure-sdk-for-ios/pull/169

Ideally we can land that PR first, then I can use those pipelines to validate the restructuring work that I'm doing here.

### CODE REVIEW

**Comment by bsiegel** [comment]
Just FYI we're trying to get #159, #168, and #171 in first, and then we can rebase this PR and merge to shuffle around all the files.

**Comment by mitchdenny** [comment]
No worries. I'll sit on this for a bit. I'm not done playing around anyway, I need to figure out way that we can isolate the pipelines but still allow AzureAppConfiguration (for example) to depend on AzureCore.

**Comment by tjprescott** [comment]
@mitchdenny all feature PRs are merged. Feel free to do the necessary restructuring or let us know what folder structure you would like and we can make it happen.

**Comment by tjprescott** [comment]
@mitchdenny with #175 merged, the simple reorganization is done, but there may be things you did in this PR that weren't done there.

**Comment by mitchdenny** [comment]
Thanks for the heads up @tjprescott

**Pull request closed without merging**
