### PR TITLE
Use macOS-11 as default pipeline image

### LINKED ISSUE #974: [BUG] CI skips running RecordableXCTestCases
CI does not run ChatClientDVRTests. Instead it skips them.

### PR DESCRIPTION
**Pull request by benbp**
Mac 11 agent capacity has finally been added to the hosted pool: https://github.com/actions/virtual-environments/issues/4060

Fixes #974

### CODE REVIEW

**Review by tjprescott — APPROVED** [review]

**Comment by benbp** [comment]
@tjprescott any update on the test issues that were blocking this (IIRC)?

**Comment by tjprescott** [comment]
@benbp I run the CI without this change and passed, so it seems there is something about running this on iOS 11 that breaks.

**Comment by benbp** [comment]
> @benbp Ben Broderick Phillips FTE I run the CI without this change and passed, so it seems there is something about running this on iOS 11 that breaks.

Ok. Do you want me to just keep this PR open until the iOS 11 issues are fixed? Or transfer it over to you or something?

**Comment by tjprescott** [comment]
@benbp if you want to push it to a branch on this repo then I can play around with it. You can also transfer the issue to me.

**Comment by tjprescott** [comment]
Looks like this is related to #975. The failing test cases ARE the recordable ones, which means this change worked! Now to figure out why they are failing :P  That's on me.

**Pull request merged**
