### PR TITLE
[Communication] - Tests - All scheme parallelize unit tests for communication 

### PR DESCRIPTION
**Pull request by JoshuaLai**

### CODE REVIEW

**Comment by bsiegel** [comment]
Hmm, we will want to test this locally / with CI. I believe we had this set on all schemes previously, and it was causing flaky test runs.

**Comment by JoshuaLai** [comment]
> Hmm, we will want to test this locally / with CI. I believe we had this set on all schemes previously, and it was causing flaky test runs.

Ah I see. I tested it locally and didn't notice any negative pop up. I'm not sure how to test the CI short of just making a bunch of PR's. But I did notice that it was just the Communication tests under the all.xcscheme that didn't have it parallel, all the others seemed to already be set to parallel

**Comment by bsiegel** [comment]
Ahh I see now. This looks good, however I've been working on a big cleanup of some of the build configuration and project files in #653 and I included the same change over there. So I might hold off on merging this and if we decide we want to merge the other PR, we can close this one.

**Comment by bsiegel** [comment]
Going to close this PR as the proposed change was included in #653 which was merged

**Pull request closed without merging**
