### PR TITLE
Update Calling README.md

### PR DESCRIPTION
**Pull request by raosanat**

### CODE REVIEW

**Comment by tjprescott** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=862037&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0&l=24
Please check the link checker errors. Otherwise, looks good!

**Comment by raosanat** [comment]
> https://dev.azure.com/azure-sdk/public/_build/results?buildId=862037&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0&l=24
> @raosanat please check the link checker errors. Otherwise, looks good!

Still some links in `AzureCommunicationCommon` Changelog is broken which is failing the build. 
https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/865548/logs/34

**Comment by tjprescott** [comment]
@raosanat you need to rebase this PR off the latest in master to resolve the errors.

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
