### PR TITLE
Prepare beta.6 release

### PR DESCRIPTION
**Pull request by bsiegel**

### CODE REVIEW

**Comment by bsiegel** [comment]
Had a test failure in "ObjCCommunciationUserCredentialTests test_ObjCRefreshTokenProactively_TokenAlreadyExpired" - no code changes here, so probably a flaky test. Re-running the unit test job now, but we should file an issue to fix the test.

**Review by raosanat — APPROVED** [review]

**Comment by bsiegel** [comment]
Re-ran tests and now I'm getting a failure in "ObjCCommunciationUserCredentialTests test_ObjCRefreshTokenProactively_FetchTokenReturnsError" @JoshuaLai can you assist? I can't see any change in this PR that would cause random tests to start failing, but if I recall you had experienced this before right?

**Review by tjprescott — APPROVED** [review]

**Comment by JoshuaLai** [comment]
> Re-ran tests and now I'm getting a failure in "ObjCCommunciationUserCredentialTests test_ObjCRefreshTokenProactively_FetchTokenReturnsError" @JoshuaLai can you assist? I can't see any change in this PR that would cause random tests to start failing, but if I recall you had experienced this before right?

@bsiegel unfortunately it looks like the tests all pass locally but only on CI it is not passing reliably. For the sake of time I have disabled the objc unit tests.

**Comment by bsiegel** [comment]
> unfortunately it looks like the tests all pass locally but only on CI it is not passing reliably. For the sake of time I have disabled the objc unit tests.

Thanks @JoshuaLai, this should unblock us. Let's make sure to file an issue to fix the flaky tests.

**Pull request merged**
